#!/bin/bash

set -x

# This is now in travis file wo we dont need to use sudo
#sudo apt-get update -qq
#sudo apt-get install -qq -y libgtk-3-dev gettext libglib2.0-dev libc6-dev-i386
#sudo apt-get install -qq -y xvfb

#
# GUI tests seems to be disabled
#
exit 0

# sudo /usr/bin/Xvfb $DISPLAY 2>&1 > /dev/null &
sh -e /etc/init.d/xvfb start
sleep 3 # wait for xvfb

# This is only for the GUI test
sudo apt-get install -qq -y python-dogtail gsettings-desktop-schemas
gsettings set org.gnome.desktop.interface toolkit-accessibility true
sudo apt-get install -qq -y libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.5-dev tk8.5-dev g++-multilib
sudo pip install --upgrade pip
sudo pip install Pillow
sudo pip install behave

